[build]
  base = "dapp"
  command = "gatsby build"
  publish = "public"

[dev]
  command = "gatsby develop"

[context.production.environment]
  SUBGRAPH_URL = "https://api.thegraph.com/subgraphs/name/protofire/synthetix-grantsdao"
  GATSBY_SUBGRAPH_NETWORK_ID = "1"

[context.deploy-preview.environment]
  SUBGRAPH_URL = "https://api.thegraph.com/subgraphs/name/protofire/synthetix-grantsdao-ropsten"
  GATSBY_SUBGRAPH_NETWORK_ID = "3"